# Day 11

In [3]:
import os

In [4]:
input_file_path = os.path.join(".", "day11_sample.txt")
with open(input_file_path, 'r') as reader:
    input_data = reader.read()

## Part 1 + 2
Keep running parse tree stack

In [28]:
import typing
import numpy as np

list_of_arr = []
for line in input_data.split("\n"):
    arr = np.fromiter(line, dtype="uint8")
    list_of_arr.append(arr)
arr = np.array(list_of_arr)

def neighbours(
    x: int, 
    y: int, 
    shape: typing.Tuple[int, int]
) -> typing.List[typing.Tuple[int, int]]:
    l = []

    has_left = (x > 0)
    has_right = (x < shape[0] - 1)
    has_top = (y > 0)
    has_bottom = (y < shape[1] - 1)

    if has_left:
        l.append((x - 1, y))
        if has_top:
            l.append((x - 1, y - 1))

    if has_top:
        l.append((x, y - 1))
        if has_right:
            l.append((x + 1, y - 1))

    if has_right:
        l.append((x + 1, y))
        if has_bottom:
            l.append((x + 1, y + 1))

    if has_bottom:
        l.append((x, y + 1))
        if has_left:
            l.append((x - 1, y + 1))

    return l

count = 0
steps = 2
for step in range(steps):
    arr += 1
    idx_flash = (arr > 9)
    flashed = set()
    while idx_flash.any():
        count += idx_flash.sum()
        for x, y in zip(*np.where(idx_flash)):
            arr[x, y] = 0

            # Make sure we only flash each tile once per step
            if (x, y) in flashed:
                continue
            flashed.add((x, y))

            # Bump all adjacent tiles
            for i, j in neighbours(x, y, arr.shape):
                if (i, i) not in flashed:
                    arr[i, j] += 1

        # Find new recursive flashes in current iteration
        idx_flash = (arr > 9)
    print(step)
    print(arr)
    print()

print(f"Part 1: after {steps:,} steps, there have been {count:,} flashes")

0
[[6 5 9 4 2 5 4 3 3 4]
 [3 8 5 6 9 6 5 8 2 2]
 [6 3 7 5 6 6 7 2 8 4]
 [7 2 5 2 4 4 7 2 5 7]
 [7 4 6 8 4 9 6 5 8 9]
 [5 2 7 8 6 3 5 7 5 6]
 [3 2 8 7 9 5 2 8 3 2]
 [7 9 9 3 9 9 2 2 4 5]
 [5 9 5 7 9 5 9 6 6 5]
 [6 3 9 4 8 6 2 6 3 7]]

1
[[8 8 1 7 4 7 5 4 4 5]
 [4 0 7 9 0 8 6 9 3 3]
 [8 5 9 7 8 8 8 5 1 8]
 [8 4 8 5 7 6 9 6 0 2]
 [8 7 0 3 9 1 8 8 2 3]
 [6 6 1 6 1 8 8 9 8 9]
 [6 8 3 3 7 0 5 9 4 3]
 [0 5 6 0 7 4 7 4 5 6]
 [9 3 3 3 6 2 2 8 7 6]
 [8 7 3 0 2 0 6 8 4 8]]

Part 1: after 2 steps, there have been 34 flashes
